Repository CanalSharp/CanalSharp, pull requests merged in 2018-09, with the labels that each got.

#2 support docker sample
  README.md
  docker/docker-compose.yml
  docker/example/instance.properties
  docker/mysql/init/init.sql
  docker/mysql/mysqld.cnf
  sample/CanalSharp.SimpleClient/Program.cs
Labels: document, enhancement

#7 FIx update readme
  README.md
  sample/CanalSharp.SimpleClient/Program.cs
Labels: document

#8 add the English version of readme
  README-en.md
Labels: document

#13 Fix Update document
  README-en.md
  README.md
  README.zh-cn.md
Labels: document

#14 fix update document
  README.md
Labels: document

#18 Add apache license header on files
  src/CanalSharp.Client/ICanalConnector.cs
  src/CanalSharp.Client/ICanalNodeAccessStrategy.cs
  src/CanalSharp.Client/Impl/CanalConnectors.cs
  src/CanalSharp.Client/Impl/Running/ClientRunningData.cs
  src/CanalSharp.Client/Impl/Running/ClientRunningMonitor.cs
  src/CanalSharp.Client/Impl/Running/IClientRunningListener.cs
  src/CanalSharp.Client/Impl/SimpleCanalConnector.cs
  src/CanalSharp.Client/Impl/SimpleNodeAccessStrategy.cs
  src/CanalSharp.Common/AbstractCanalLifeCycle.cs
  src/CanalSharp.Common/Alarm/ICanalAlarmHandler.cs
  src/CanalSharp.Common/Alarm/Impl/LogAlarmHandler.cs
  src/CanalSharp.Common/Exception/CanalException.cs
  src/CanalSharp.Common/ICanalLifeCycle.cs
  src/CanalSharp.Common/Logging/CanalSharpLogManager.cs
  src/CanalSharp.Common/Utils/AddressUtils.cs
  src/CanalSharp.Common/Utils/BooleanMutex.cs
  src/CanalSharp.Common/Zookeeper/Running/IServerRunningListener.cs
  src/CanalSharp.Protocol/ClientIdentity.cs
  src/CanalSharp.Protocol/Exception/CanalClientException.cs
  src/CanalSharp.Protocol/Message.cs
  src/CanalSharp.Protocol/Position/EntryPosition.cs
  src/CanalSharp.Protocol/Position/LogIdentity.cs
  src/CanalSharp.Protocol/Position/LogPosition.cs
  src/CanalSharp.Protocol/Position/MetaqPosition.cs
  src/CanalSharp.Protocol/Position/Position.cs
  src/CanalSharp.Protocol/Position/PositionRange.cs
  src/CanalSharp.Protocol/Position/TimePosition.cs
Labels: enhancement
